export { default as commentRouter } from './comment'
export { default as likeRouter } from './like'
export { default as postRouter } from './post'
export { default as userRouter } from './user'
export { default as authRouter } from './auth'
